#ifndef _REGISTER_CONSTS
#define _REGISTER_CONSTS

enum
{
	ANALOGIN_COUNTR = 22,
	ANGLEOUT_COUNTR = 10,
	ARINCIN_COUNTR = 5,
	ARINCOUT_COUNTR = 6,
	ARINCWORD_COUNTR = 14,
	CHECKER_COUNTR = 3,
	COMMAND_COUNTR = 5,
	FREQUENCYIN_COUNTR = 7,
	POTENTIOMETRIN_COUNTR = 15,
	NPTOUT_COUNTR = 8,
	RSIN_COUNTR = 6,
	RSOUT_COUNTR = 6,
	LOGICALIN_COUNTR = 9,
	LOGICALOUT_COUNTR = 9
};

#endif

